install: true
jdk:
  - oraclejdk8
before_script: ./profiles-install.sh
jobs:
  include:
    - stage: test
      script: ./vue.sh
    -
      script: ./react.sh
#    - stage: web
#      script: ./web.sh
#    - stage: rest-api
#      script: ./rest-api.sh
#    - stage: react
#      script: ./react.sh
#    - stage: profile
#      script: ./profile.sh
#    - stage: web-jboss7
#      script: ./web-jboss7.sh
#    - stage: plugin
#      script: ./plugin.sh
#    - stage: web-plugin
#      script: ./web-plugin.sh
#    - stage: rest-api-plugin
#      script: ./rest-api-plugin.sh
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
