install: true
jdk:
  - oraclejdk8
script:
  - curl -s get.sdkman.io | bash
  - source "$HOME/.sdkman/bin/sdkman-init.sh"
  - echo sdkman_auto_answer=true > ~/.sdkman/etc/config
  - source "/home/travis/.sdkman/bin/sdkman-init.sh"
  - ./gradlew build --console=plain
  - cd build/grails-wrapper/
  - ./gradlew assemble
  - cd ../../
  - mkdir -p $HOME/.grails/wrapper
  - cp /home/travis/build/grails/grails-profiles-tests/build/grails-wrapper/wrapper/build/libs/grails4-wrapper-1.0.1.BUILD-SNAPSHOT.jar $HOME/.grails/wrapper/grails4-wrapper.jar
  - sdk install grails dev /home/travis/build/grails/grails-profiles-tests/build/grails-core
  - sdk install grails
  - sdk use grails dev
  - grails --version
# ******************************************************
# ***************** WEB profile ************************
  - grails create-app demo --profile=org.grails.profiles:web:4.0.0.BUILD-SNAPSHOT
  - cd demo
  - touch settings.gradle
# ***************** base profiles command **************
  - ./grailsw assemble
  - ./grailsw package # synonym of grails assemble
  - ./grailsw war # synonym of grails assemble
  - ./grailsw bug-report
  - ./grailsw clean
  - ./grailsw compile
#  - ./grailsw console
  - ./grailsw create-command awesome
  - ./grailsw create-domain-class Book
  - ./grailsw create-script scripto
  - ./grailsw create-service BookService
  - ./grailsw create-unit-test Foo
  - ./grailsw dependency-report
  - ./grailsw list-plugins
  - ./grailsw plugin-info geb
#  - ./grailsw run-app
#  - ./grailsw run-command
#  - ./grailsw run-script
#  - ./grailsw shell
  - ./grailsw stats
#  - ./grailsw stop-app
# ***************** web profiles command **************
  - ./grailsw create-controller Company
  - ./grailsw create-integration-test Int
  - ./grailsw create-interceptor Company
  - ./grailsw create-taglib Currency
# ***************** base profiles command **************
  - cd ..
  - ./gradlew fixTests
  - cd demo
  - ./grailsw test-app
  # ******************************************************
  # ************** rest-api profile **********************
  - cd ..
  - rm -rf demo
  - grails create-app demo --profile=org.grails.profiles:rest-api:4.0.0.BUILD-SNAPSHOT
  - cd demo
  - touch settings.gradle
  # ***************** base profiles command **************
  - ./grailsw assemble
  - ./grailsw package # synonym of grails assemble
  - ./grailsw war # synonym of grails assemble
  - ./grailsw bug-report
  - ./grailsw clean
  - ./grailsw compile
  #  - ./grailsw console
  - ./grailsw create-command awesome
  - ./grailsw create-domain-class Book
  - ./grailsw create-script scripto
  - ./grailsw create-service BookService
  - ./grailsw create-unit-test Foo
  - ./grailsw dependency-report
  - ./grailsw list-plugins
  - ./grailsw plugin-info geb
  #  - ./grailsw run-app
  #  - ./grailsw run-command
  #  - ./grailsw run-script
  #  - ./grailsw shell
  - ./grailsw stats
  #  - ./grailsw stop-app
  # ***************** rest-api profiles command **************
  - ./grailsw create-controller Company
  - ./grailsw create-domain-resource Car
  - ./grailsw create-functional-test Func
  - ./grailsw create-integration-test Int
  - ./grailsw create-interceptor Company
  - ./grailsw create-domain-class Employee
  - ./grailsw create-restful-controller Employee
  #- ./grailsw generate-unit-test
  - ./grailsw create-domain-class Device
  - ./grailsw generate-controller Device
  - ./grailsw generate-views Device
  # - ./grailsw generate-functional-test Device # TODO Fails
  # ***************** base profiles command **************
  - cd ..
  - ./gradlew fixTests
  - cd demo
  - ./grailsw test-app
  # ******************************************************
  # ************** puglin profile **********************
  - cd ..
  - rm -rf demo
  - grails create-app demo --profile=org.grails.profiles:plugin:4.0.0.BUILD-SNAPSHOT --type plugin
  - cd demo
  - touch settings.gradle
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
